### ISSUE TITLE
Prepare Pizza to bake

### ISSUE THREAD

**Issue by eliewa** [Warjumper/Kanban-pizza#3]

**Comment by Warjumper** [comment]
## Instructions

When the oven is ready, dust a pizza peel with cornmeal or semolina flour. (If you don’t have a pizza peel, you can use a rimless baking sheet or the back of a rimmed baking sheet. But a pizza peel is well worth the investment!) Stretch the dough into a circle; see [How to Stretch Pizza Dough](https://www.acouplecooks.com/how-to-stretch-pizza-dough/) for instructions. Then gently place the dough onto the pizza peel.

**Comment by Warjumper** [comment]
Ensure oven is 500f.

**Comment by myka-p** [comment]
prep done

**Comment by Warjumper** [comment]
@myka-p Thank you!
