### ISSUE TITLE
Purchase ingredients

### ISSUE THREAD

**Issue by Warjumper** [Warjumper/Kanban-pizza#6]
## Ingredients

- 1 ball [Best Pizza Dough](https://www.acouplecooks.com/how-to-make-pizza-dough/) (or [Food Processor Dough]- (https://www.acouplecooks.com/easy-food-processor-pizza-dough/) or [Thin Crust Dough](https://www.acouplecooks.com/easy-thin-crust-pizza-dough/))
- ⅓ cup [Best Homemade Pizza Sauce](https://www.acouplecooks.com/homemade-easy-pizza-sauce-recipe/)
- 2 to 3 ounces fresh mozzarella cheese
- 6 anchovy fillets from a jar or can
- 8 Kalamata olives
- 1 handful thinly sliced red onion
- Parmesan or Pecorino cheese, for grating
- Semolina flour or cornmeal, for dusting the pizza peel

**Comment by darbecker12** [comment]
What is your favourite dough to use? sounds like a great recipe

**Comment by Warjumper** [comment]
I prefer the thin crust myself.
